name: Resume Instances Workflow

on:
  # Triggers the workflow to run automatically using a cron job
  #schedule:
  #  - cron: '0 20 * * *'
    
  workflow_dispatch:

jobs:
  pause-instances:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.x'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run resume instances script
      env:
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_PWD: ${{ secrets.CLIENT_PWD }}
        TENANT_ID: ${{ secrets.TENANT_ID }}

      run: |
        python resume_instances.py